name: Automatisation des tests DevSecOps

on: push

jobs:
  Dependances:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Vérifier et installer requirements.txt
        run: |
          test -f requirements.txt || {
            echo "::error file=requirements.txt::Fichier requirements.txt introuvable";
            exit 1;
          }
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip check

  Dockerfile:
    runs-on: ubuntu-latest
    needs: Dependances
    steps:
      - name: Récupérer le code
        uses:
